# Site settings
author: AJ
title: Adding Gears
header-img: img/home-bg.png
email: aj.no.limit.1@gmail.com
copyright_name: AJ
description: > # this means to ignore newlines until "baseurl:"
  AG
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  blockfinni

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
